FROM liyaosong/ubuntu:noble AS base

ARG VERSION="Ubuntu 24.04"

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    ninja-build \
    git \
    pkg-config \
    wget \
    ca-certificates \
    zlib1g-dev \
    libssl-dev \
    libdbus-1-dev \
    libudev-dev \
    libdrm-dev \
    libgbm-dev \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    libx11-dev \
    libxext-dev \
    libxrender-dev \
    libx11-xcb-dev \
    libxkbcommon-dev \
    libwayland-dev \
    libwayland-egl1-mesa \
    libxrandr-dev \
    libxcursor-dev \
    libxfixes-dev \
    libxinerama-dev \
    libxi-dev \
    libxv-dev \
    libfreetype-dev \
    libfontconfig1-dev \
    libjpeg-dev \
    libpng-dev \
    libzstd-dev \
    libpcre2-dev \
    libvulkan1 \
    vulkan-tools \
    libvulkan-dev \
    mesa-vulkan-drivers \
    libgl1-mesa-dev \
    spirv-tools \
    spirv-headers \
    glslang-tools \
    spirv-cross \
    libicu-dev \
    libxcb1 \
    libglu1-mesa-dev \
    xutils-dev \
    '^libxcb.*-dev' \
    libxkbcommon-x11-dev \
    libgtk-3-0 \
    libgtk-3-dev \
    libgdk-pixbuf-2.0-dev \
    libpango1.0-dev \
    libatk1.0-dev \
    libcairo2-dev \
    libglib2.0-0 \
    libglib2.0-dev \
    libgirepository1.0-dev \
    gir1.2-glib-2.0 \
    libpulse0 \
    libpulse-dev \
    libpulse-mainloop-glib0 \
    libasound2-dev \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    gstreamer1.0-tools \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    ffmpeg \
    libavcodec-dev \
    libavformat-dev \
    libavutil-dev \
    libswscale-dev \
    pipewire \
    libpipewire-0.3-dev \
    libpipewire-0.3-0 \
    libva-dev \
    vainfo \
    bluez \
    libbluetooth-dev \
    bluez-tools \
    clang \
    libclang-dev \
    libopus-dev \
    libsnappy-dev \
    libminizip-dev \
    libevent-dev \
    libxml2-dev \
    libxslt1-dev \
    liblcms2-dev \
    libpci-dev \
    llvm \
    llvm-dev \
    clang-14 \
    llvm-14-dev \
    libclang-14-dev \
    nodejs \
    gperf \
    bison \
    flex \
    libnss3-dev \
    libnss3-tools \
    libxkbfile-dev \
    libxshmfence-dev \
    speech-dispatcher \
    libspeechd-dev \
    libgrpc++-dev \
    libgrpc-dev \
    libprotoc-dev \
    protobuf-compiler-grpc \
    protobuf-compiler \
    libprotobuf-dev \
    libgphoto2-6 \
    libgphoto2-dev \
    libgstreamer-plugins-bad1.0-dev \
    libmariadb-dev-compat \
    unixodbc-dev \
    libpq-dev && apt-get autoremove -y && apt-get clean && \
    rm -rf \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/* \
    /root/.cache \
    /var/cache/apt/archives/*.deb \
    /var/cache/apt/*.bin \
    /var/lib/apt/lists/* \
    /usr/share/*/*/*/*.gz \
    /usr/share/*/*/*.gz \
    /usr/share/*/*.gz \
    /usr/share/doc/*/README* \
    /usr/share/doc/*/*.txt \
    /usr/share/locale/*/LC_MESSAGES/*.mo 

LABEL maintainer="liyaosong <liyaosong1@qq.com>"
LABEL version=${VERSION}
LABEL description="Qt source build Docker image based on Ubuntu 24.04."
