#!/bin/bash

# 启用 BuildKit
export DOCKER_BUILDKIT=1

# 设置 Buildx Builder 并启用 sbom 和 provenance
docker buildx create --use

docker buildx build --sbom=true --provenance=true --platform linux/amd64,linux/arm64 -t $IMAGE_NAME . --push
